### ISSUE TITLE
Segmentation fault with configuring only-pmem, threshold or ratio in memory-alloc-policy when launching redis-server

### ISSUE THREAD

**Issue by jiawen11** [memKeyDB/memKeyDB#110]
Hi,

When I configured the `memory-alloc-policy` as`only-pmem`, `threshold` or `ratio` and launched `/redis-server memKeyDB/redis.conf`, I got the following errors. Configuring with `only-dram` is no problem. The Intel Optane is configured by https://pmem.io/2020/01/20/memkind-dax-kmem.html, and I tested that the Intel Optane configuration is no problem as well. I configured memory-alloc-policy in redis.conf.

Besides, I follow https://memkeydb.io/about with the following to enable memkind in malloc:
git submodule init
git submodule update
make MALLOC=memkind

Please let me know if you have any ideas of how to address the following issue.

Thanks!

```
$ ./redis-server memKeyDB/redis.conf
37014:C 22 Apr 2021 23:58:23.087 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
37014:C 22 Apr 2021 23:58:23.087 # Redis version=6.0.9, bits=64, commit=58c4f393, modified=1, pid=37014, just started
37014:C 22 Apr 2021 23:58:23.087 # Configuration loaded
37014:M 22 Apr 2021 23:58:23.088 * Increased maximum number of open files to 10032 (it was originally set to 1024).


=== REDIS BUG REPORT START: Cut & paste starting from here ===
37014:M 22 Apr 2021 23:58:23.090 # Redis 6.0.9 crashed by signal: 11, si_code: 1
37014:M 22 Apr 2021 23:58:23.090 # Crashed running the instruction at: 0x7f7d287affce
37014:M 22 Apr 2021 23:58:23.090 # Accessing address: (nil)
37014:M 22 Apr 2021 23:58:23.090 # Killed by PID: 0, UID: 0
37014:M 22 Apr 2021 23:58:23.090 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(__vsnprintf_chk+0x7e)[0x7f7d287affce]

Backtrace:
/home/memKeyDB_install/bin/redis-server 127.0.0.1:6379(logStackTrace+0x45)[0x561347621315]
/home/memKeyDB_install/bin/redis-server 127.0.0.1:6379(sigsegvHandler+0xd5)[0x561347621af5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f7d28a81980]
/lib/x86_64-linux-gnu/libc.so.6(__vsnprintf_chk+0x7e)[0x7f7d287affce]
/lib/x86_64-linux-gnu/libc.so.6(__snprintf_chk+0x85)[0x7f7d287aff25]
/home/memKeyDB_install/bin/redis-server 127.0.0.1:6379(redisAsciiArt+0xde)[0x5613475dce8e]
/home/memKeyDB_install/bin/redis-server 127.0.0.1:6379(main+0x37c)[0x5613475ce3ec]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f7d2869fbf7]
/home/memKeyDB_install/bin/redis-server 127.0.0.1:6379(_start+0x2a)[0x5613475ce89a]

------ INFO OUTPUT ------
Segmentation fault (core dumped)
```

**Comment by jschmieg** [comment]
Hi,
it looks like the first allocation which targets pmem is unsuccessful. It may be related to incorrect kmem-dax configuration. Could you please verify output of 
_numactl -H_
if there is NUMA node dedicated to dax kmem (Node without CPUs, only with memory).

Another thing to verify is to ensure if memkind was compiled with daxctl support. You should see:
_Automatic recognition of PMEM NUMA in MEMKIND_DAX_KMEM is enabled_ 
during memkind configuration step (you may need to clean all memkind binaries and rebuild memkind).
If daxctl was not present during memkind build process, then it is still possible to use KMEM DAX, but you need to manually set KMEM DAX NUMA node to be used by application with MEMKIND_DAX_KMEM_NODES environment variable: [kmem dax blog](https://pmem.io/2020/01/20/memkind-dax-kmem.html).
Best regards

**Comment by jiawen11** [comment]
Thanks! I've already addressed this issue.
