### ISSUE TITLE
oom under only-pmem mode with fsdax with much capacity available

### ISSUE THREAD

**Issue by freecw** [memKeyDB/memKeyDB#67]
Trying to run redis-benchmark with -n 10000000 -r 10000000 -d 1024 with redis-server configured with only-pmem. When used_memory_pmem reached about 12~15GB, oom happened with memkind_realloc returning NULL. There are still much pmem space available (with only 5% used). No maxmemory configured for the redis-server.

#cat /etc/mtab | grep pmem
/dev/pmem0 /mnt/cwtest ext4 rw,relatime,dax,data=ordered 0 0

Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/pmem0           511009272  20139280 464842472   5% /mnt/cwtest

branch: 6.0.9-devel

**Comment by jschmieg** [comment]
Hi, thanks for your contact.
MemKeyDB only-pmem will not allocate memory from FS DAX (/mnt/cwtest/ in your case). MemKeyDB uses Memkind library with memory kind created on KMEM DAX (so memory exposed as NUMA node, not as device with File System). You can read how to reconfigure your system to KMEM DAX enabled here (requires Linux kernel 5.1 or above):
[https://pmem.io/2020/01/20/memkind-dax-kmem.html](https://pmem.io/2020/01/20/memkind-dax-kmem.html)

**Comment by freecw** [comment]
Hi, thanks. I modify the code as our nvdimm has been configured with fsdax namespace. And I suppose it should work.

memkind_t pmem_kind = NULL;
void set_pmem_kind(void) {
    memkind_create_pmem("/mnt/cwtest/", 0, &pmem_kind);
}

static void *zrealloc_pmem(void *ptr, size_t size) {
#ifndef HAVE_MALLOC_SIZE
    void *realptr;
#endif
    size_t oldsize;
    void *newptr;

    if (size == 0 && ptr != NULL) {
        zfree_pmem(ptr);
        return NULL;
    }
    if (ptr == NULL) return zmalloc(size);
#ifdef HAVE_MALLOC_SIZE
    oldsize = zmalloc_size(ptr);
    //newptr = realloc_pmem(ptr,size);
    **newptr =  memkind_realloc(pmem_kind,ptr,size);**
    if (!newptr) {
        zmalloc_oom_handler(size);
    }

    update_zmalloc_pmem_stat_free(oldsize);
    update_zmalloc_pmem_stat_alloc(zmalloc_size(newptr));
    return newptr;
#else
    realptr = (char*)ptr-PREFIX_SIZE;
    oldsize = *((size_t*)realptr);
    //newptr = realloc_pmem(realptr,size+PREFIX_SIZE);
    newptr =  memkind_realloc(pmem_kind,realptr,size);
    if (!newptr) zmalloc_oom_handler(size);

    *((size_t*)newptr) = size;
    update_zmalloc_pmem_stat_free(oldsize+PREFIX_SIZE);
    update_zmalloc_pmem_stat_alloc(size+PREFIX_SIZE);
#endif
}

**Comment by jschmieg** [comment]
Please share whole your modification.
We intentionally used KMEM_DAX instead of dynamic pmem_kind on FS DAX, as the latter doesn't support Copy-on-Write feature which is used by Redis in RDB snapshots, AOF rewriting, and replication. So FSDAX approach is very limited in functionality.

**Comment by freecw** [comment]
Yes I understand. 

rest of change.

server.c:5199 in main():

**set_pmem_kind();**
zmalloc_set_oom_handler(redisOutOfMemoryHandler);: 

zmallloc.h:

**void set_pmem_kind();**

zmalloc.c:

static void *zmalloc_pmem(size_t size) {
    **//void *ptr = memkind_malloc(MEMKIND_DAX_KMEM, size+PREFIX_SIZE);
    void *ptr  = memkind_malloc(pmem_kind, size+PREFIX_SIZE);**
        if (!ptr) {
                fprintf(stderr, "Unable allocate in file-backed memory.\n");
        }
        if (!ptr && errno==ENOMEM) zmalloc_oom_handler(size);
#ifdef HAVE_MALLOC_SIZE
    update_zmalloc_pmem_stat_alloc(zmalloc_size(ptr));
    return ptr;
#else
    *((size_t*)ptr) = size;
    update_zmalloc_pmem_stat_alloc(size+PREFIX_SIZE);
    return (char*)ptr+PREFIX_SIZE;
#endif
}

static void *zcalloc_pmem(size_t size) {
    **//void *ptr = memkind_calloc(MEMKIND_DAX_KMEM, 1, size+PREFIX_SIZE);
        void *ptr  = memkind_calloc(pmem_kind, 1, size+PREFIX_SIZE);**
        if (!ptr) {
                fprintf(stderr, "Unable allocate in file-backed memory.\n");
        }
    if (!ptr && errno==ENOMEM) zmalloc_oom_handler(size);
#ifdef HAVE_MALLOC_SIZE
    update_zmalloc_pmem_stat_alloc(zmalloc_size(ptr));
    return ptr;
#else
    *((size_t*)ptr) = size;
    update_zmalloc_pmem_stat_alloc(size+PREFIX_SIZE);
    return (char*)ptr+PREFIX_SIZE;
#endif
}

**Comment by jschmieg** [comment]
Do you have this modification available on GitHub? Please share your branch.

**Comment by freecw** [comment]
this is my pr against memkeyDB 6.0.9-devel 
https://github.com/freecw/memKeyDB/pull/1/files

**Comment by jschmieg** [comment]
I did some correction to your code in order to compile it and I run server in only-pmem ( I disabled RDB feature in config as I described previously) and run benchmark:
./src/redis-benchmark -t set -n 10000000 -r 10000000 -d 1024
I did run it like 10 times, the database size reached around 15GB, and wasn't able to reproduce error. Can you give the exact steps of your configuration of server and benchmark?

**Comment by freecw** [comment]
Thanks. 

server is run with "taskset -c 5 ./src/redis-server --memory-alloc-policy only-pmem --protected-mode no" and benchmark is run with "taskset -c 97 ./src/redis-benchmark -h xx -p xx -t set -n 10000000 -r 10000000 -d 4096 -e". Other configuration is by default. Strangely, I ran it again the other day and no OOM until pmem was used up. I will confirm with more test. Close this issue for now. Thanks for your effort.
